KartBox/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from products.views import FeaturedProduct

urlpatterns = [
    path('admin/', admin.site.urls),
    path('account/', include('account.urls')),
    path('products/', include('products.urls')),
    path('carts/', include('carts.urls')),
    path('', FeaturedProduct.as_view(), name='home'),
    path('order/', include('checkout.urls')),
    path('address/', include('addresses.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    # urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

carts/urls.py
from django.conf.urls import url
from .views import add_cart, cart_detail, cart_remove, remove, cart_update, shippment_cost

app_name = 'carts'


urlpatterns = [
    url(r'^$', cart_detail, name='details'),
    url(r'^cart_add/(?P<product_id>[0-9]+)/$', add_cart, name='add'),
    url(r'^plus/(?P<product_id>[0-9]+)/$', cart_update, name='cart_plus'),
    url(r'^minus/(?P<product_id>[0-9]+)/$', cart_remove, name='cart_minus'),
    url(r'^remove/(?P<id>\d+)/$', remove, name='delete'),
    url(r'^shiping/$', shippment_cost, name='ship_cost'),
]

#

checkout/urls.py
from django.conf.urls import url
from .views import checkout_home, checkout_finish, checkout_success

app_name = 'order'

urlpatterns = [
    url(r'^$', checkout_home, name='checkout'),
    url(r'^done/$', checkout_finish, name='checkout_done'),
    url(r'^success/$', checkout_success, name='success')
]

products/urls.py
from django.urls import path
from .views import ProductList, ProductDetails

app_name = 'products'


urlpatterns = [
    path('list', ProductList.as_view(), name='list'),
    path('details/<slug:slug>', ProductDetails.as_view(), name='details'),
]

carts/models.py
from django.db import models
from django.conf import settings
from products.models import Product
from django.db.models.signals import pre_save, post_delete, post_save

User = settings.AUTH_USER_MODEL


class CartManager(models.Manager):
    def new_or_get(self, request):
        cart_id = request.session.get('cart_id', None)
        qs = self.get_queryset().filter(id=cart_id)
        if qs.count() == 1:
            new_obj = False
            cart_obj = qs.first()
            if request.user.is_authenticated and cart_obj.user is None:
                cart_obj.user = request.user
                cart_obj.save()
        else:
            cart_obj = self.new(user=request.user)
            new_obj = True
            request.session['cart_id'] = cart_obj.id

        return cart_obj, new_obj

    def new(self, user=None):
        user_obj = None
        if user is not None:
            if user.is_authenticated:
                user_obj = user
            else:
                user_obj = None
        return self.model.objects.create(user=user_obj)


class ShippingMethod(models.Model):
    title = models.CharField(max_length=25)
    cost = models.DecimalField(max_digits=10, decimal_places=2, default=0)

    def __str__(self):
        return self.title


class Cart(models.Model):
    user = models.ForeignKey(User, blank=True, null=True, on_delete=models.CASCADE)
    products = models.ManyToManyField(Product, blank=True)
    shipping_method = models.ForeignKey(ShippingMethod, blank=True, null=True, on_delete=models.SET_NULL)
    created = models.DateTimeField(auto_now_add=True, auto_now=False)
    updated = models.DateTimeField(auto_now_add=False, auto_now=True)
    active = models.BooleanField(default=True)
    total = models.DecimalField(max_digits=10, decimal_places=2, default=0)

    objects = CartManager()

    def __str__(self):
        return f'Cart Id: {self.pk}'


class CartItem(models.Model):
    cart = models.ForeignKey(Cart, null=True, blank=True, on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    quantity = models.PositiveIntegerField(default=0)
    total_item_price = models.DecimalField(max_digits=10, decimal_places=2, default=0)

    def __str__(self):
        return self.product.name


def get_single_total(instance, **kwargs):
        if int(instance.quantity) >= 1:
            total = float(instance.product.price) * int(instance.quantity)
            instance.total_item_price = total


pre_save.connect(get_single_total, sender=CartItem)


def user_presave(instance, **kwargs):
    if not instance.user:
        user = instance.user
        return user
    else:
        return instance.user


pre_save.connect(user_presave, sender=Cart)


def total_cost(instance, **kwargs):
    if instance.shipping_method:
        total = float(instance.total) + float(instance.shipping_method.cost)
        instance.total = total


pre_save.connect(total_cost, sender=Cart)

carts/forms.py
from django import forms
from .models import ShippingMethod


class ShipForm(forms.Form):
    shipment = forms.ModelChoiceField(queryset=ShippingMethod.objects.all().order_by('-title'))

carts/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import render, get_object_or_404, redirect
from django.urls import reverse
from products.models import Product
from .models import Cart, CartItem, ShippingMethod


def cart_detail(request):
    cart, created = Cart.objects.new_or_get(request)
    ship_obj = ShippingMethod.objects.all()
    if not created:
        new_total = 0
        for item in cart.cartitem_set.all():
            total = float(item.product.price) * item.quantity
            new_total += total
        cart.total = new_total
        cart.save()

    context = {
        'cart': cart,
        'ship_obj': ship_obj,
    }
    return render(request, 'carts/cart_details.html', context)


def shippment_cost(request):
    cart, created = Cart.objects.new_or_get(request)
    try:
        ship_in = request.POST.get('method', None)
    except:
        raise ValueError('Mara khawa sara! :(')
    cart_ship = ShippingMethod.objects.get(id=int(ship_in))
    if cart_ship:
        cart.shipping_method = cart_ship
        cart.save()
    return HttpResponseRedirect(reverse('carts:details'))


def add_cart(request, product_id):
    cart, created = Cart.objects.new_or_get(request)
    product = get_object_or_404(Product, id=product_id)
    try:
        quantity = request.POST['qty']
        qty = True
    except:
        quantity = None
        qty = False

    cart_item, create = CartItem.objects.get_or_create(cart=cart, product=product)
    if cart_item:
        cart_item.quantity += int(quantity)
    else:
        cart_item.quantity = int(quantity)
    cart_item.save()
    # return HttpResponseRedirect(reverse('carts:details'))
    return redirect(request.META['HTTP_REFERER'])


def cart_update(request, product_id):
    cart, created = Cart.objects.new_or_get(request)
    product = get_object_or_404(Product, id=product_id)
    try:
        quantity = request.POST['qty']
        qty = True
    except:
        quantity = None
        qty = False

    cart_item, create = CartItem.objects.get_or_create(cart=cart, product=product)
    if cart_item:
        cart_item.quantity += 1
    else:
        cart_item.quantity = int(quantity)
    cart_item.save()
    # return HttpResponseRedirect(reverse('carts:details'))
    return redirect(request.META['HTTP_REFERER'])


def cart_remove(request, product_id):
    cart, created = Cart.objects.new_or_get(request)
    product = get_object_or_404(Product, id=product_id)
    # cart_item, create = CartItem.objects.get_or_create(cart=cart, product=product)
    cart_item = CartItem.objects.get(cart=cart, product=product)
    print(cart_item)
    if cart_item.quantity > 1:
        cart_item.quantity -= 1
        cart_item.save()
    else:
        cart_item.delete()
    # return HttpResponseRedirect(reverse('carts:details'))
    return redirect(request.META['HTTP_REFERER'])


def remove(request, id):
    cart, created = Cart.objects.new_or_get(request)
    cart_item = CartItem.objects.get(id=id)
    cart_item.cart = None
    # cart_item.delete()
    cart_item.save()
    return HttpResponseRedirect(reverse('carts:details'))

carts/templates/carts/cart_details.html
{% extends 'master.html' %}
{% load static %}
{% block title %}
Cart Details
{% endblock %}


{#{% block content %}#}
{#{% if cart_count %}#}
{#<div class="container col-sm-8 offset-2 mt-5">#}
{#<form method="POST"></form>#}
{#<table class="container" style="margin-top: 60px">#}
{#<p class="text-center text-capitalize" style="margin-top: 100px">cart count: {{ cart_count }}</p>#}
{#    <thead>#}
{#    <th class="text">Product</th>#}
{#    <th class="text">Quantity</th>#}
{#    <th class="text">Price</th>#}
{#    </thead>#}
{#            {% for item in cart.cartitem_set.all %}#}
{##}
{#    <tr>#}
{#        <td class="text">{{ item.product.name }}</td>#}
{#        <td>#}
{#          <a href="{% url 'carts:cart_plus' product_id=item.product.id %}"><i class="fas fa-plus-circle text-dark"></i></a>#}
{#                        {{ item.quantity }}#}
{#            &nbsp;<a href="{% url 'carts:cart_minus' product_id=item.product.id %}"><i class="fas fa-minus-circle text-dark"></i></a>#}
{#        </td>#}
{#        <td class="text">{{ item.total_item_price }}</td>#}
{#        <td>#}
{#            <a href="{% url 'carts:update' product_id=item.product.id %}?qty=0">Delete</a>#}
{#            <a href="{% url 'carts:delete' id=item.id %}"><i class="fa fa-trash text-danger" aria-hidden="true"></i></a>#}
{##}
{#        </td>#}
{#    </tr>#}
{#            {% endfor %}#}
{#    <tr>#}
{#        <td>{{ cart.shipping_method.title }}</td>#}
{#        <td></td>#}
{#        <td>{{ cart.shipping_method.cost }}</td>#}
{#    </tr>#}
{#    <tr>#}
{#        <td>#}
{#            <form method="POST" action="{% url 'carts:ship_cost' %}">#}
{#            <div class="form-group form-inline">#}
{#                <label for="drop">Shipping Method: </label>#}
{#                    {% csrf_token %}#}
{#                            <select name="method" id="drop" class="form-control ml-2" style="width: 200px">#}
{#                                {% for shipping in ship_obj %}#}
{#                                    <option value="{{ shipping.id }}">{{ shipping.title }}</option>#}
{#                                {% endfor %}#}
{#                            </select>#}
{##}
{#                <input type="submit" value="Submit">#}
{##}
{#                    <button type="submit" class="btn rounded-circle ml-1 bg-transparent"><i class="fas fa-sync"></i></button>#}
{#            </div>#}
{#            </form>#}
{##}
{#        </td> <td></td>#}
{#        <td class="form-text">{{ cart.shipping_method.cost }}</td>#}
{#    </tr>#}
{##}
{#<hr>#}
{#<tfoot>#}
{#</tfoot>#}
{#</table>#}
{#</div>#}
{#<hr>#}
{#    <div class="float-right">#}
{#        <h1>Total: {{ cart.total|floatformat:2 }} + {{ cart.shipping_method.cost }}({{ cart.shipping_method.title }})</h1>#}
{#        <a type="submit" class="btn btn-success text-center" href="{% url 'order:checkout' %}">Checkout</a>#}
{#    </div>#}
{##}
{#{% else %}#}
{#    <div class="container" style="margin-top: 25%">#}
{#        <div class="row justify-content-center align-items-center">#}
{#            <form class="col-12">#}
{#              <div class="form-group">#}
{#                  <h1 class="text text-center text-justify">Buy Some Products</h1>#}
{#                  <a class="btn btn-link btn-block text-center text-justify btn" href="{% url 'products:list' %}"> Click heare to visit Shop</a>#}
{#              </div>#}
{#            </form>#}
{#        </div>#}
{#    </div>#}
{#        {% endif %}#}
{##}
{#{% endblock %}#}


{#/////////////////// Template#}


{% block content %}
{% if cart_count %}
<div class="card" style="padding-top: 70px">
  <div class="card-body">

    <!-- Shopping Cart table -->
    <div class="table-responsive">

      <table class="table product-table">

        <!-- Table head -->
        <thead class="mdb-color lighten-5">
          <tr>
            <th></th>
            <th class="font-weight-bold">
              <strong>Product</strong>
            </th>
            <th></th>
            <th class="font-weight-bold">
              <strong>Price</strong>
            </th>
              <th></th>
            <th class="font-weight-bold">
              <strong>QTY</strong>
            </th>
            <th class="font-weight-bold">
              <strong>Amount</strong>
            </th>
            <th></th>
          </tr>
        </thead>
        <!-- /.Table head -->

        <!-- Table body -->
        <tbody>
        {% for item in cart.cartitem_set.all %}
          <!-- First row -->
          <tr>
            <th scope="row">
              <img src="{{ item.product.preview.url }}" width="280px" height="60px" alt="" class="img-fluid z-depth-0">
            </th>
            <td>
              <h5 class="mt-3">
                <strong>{{ item.product.name }}</strong>
              </h5>
              <p class="text-muted">{{ item.product.name }}</p>
            </td>
            <td></td>
            <td>{{ item.product.price }}</td>
              <td></td>
{#            <td>#}
{#              <input type="number" value="2" aria-label="Search" class="form-control" style="width: 100px">#}
{#            </td>#}
            <td>
                <a href="{% url 'carts:cart_plus' product_id=item.product.id %}"><i class="fas fa-plus-circle text-dark"></i></a>
                        {{ item.quantity }}
            &nbsp;   <a href="{% url 'carts:cart_minus' product_id=item.product.id %}"><i class="fas fa-minus-circle text-dark"></i></a>
            </td>
            <td class="font-weight-bold">
              <strong>{{ item.total_item_price }}$</strong>
            </td>
            <td>
              <button type="button" onclick="location.href='{% url 'carts:delete' id=item.id %}'" class="btn btn-sm btn-primary" data-toggle="tooltip" data-placement="top"
                title="Remove item">X
              </button>
            </td>
          </tr>
                    {% endfor %}

          <!-- /.First row -->
{#shipping start#}
    <tr>
        <td>{{ cart.shipping_method.title }}</td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td class="font-weight-bold"><strong>{{ cart.shipping_method.cost }}</strong></td>
        <td></td>
    </tr>
    <tr>
        <td>
            <form method="POST" action="{% url 'carts:ship_cost' %}">
            <div class="form-group form-inline">
                <label for="drop">Shipping Method: </label>
                    {% csrf_token %}
                            <select name="method" id="drop" class="form-control ml-2" style="width: 200px">
                                {% for shipping in ship_obj %}
                                    <option value="{{ shipping.id }}">{{ shipping.title }}</option>
                                {% endfor %}
                            </select>

{#                <input type="submit" value="Submit">#}
                <button type="submit" class="btn btn-sm border ml-1 bg-transparent"><i class="fas fa-sync"></i></button>
            </div>
            </form>

        </td>
        <td></td>
    <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td class="font-weight-bold"><strong>{{ cart.shipping_method.cost }}</strong></td>
        <td></td>
{#    </tr>#}
{# shipping end #}
          <!-- Fourth row -->
          <tr>
            <td colspan="3"></td>
            <td>
              <h4 class="mt-2">
                <strong>Total</strong>
              </h4>
            </td>
            <td class="text-right">
              <h4 class="mt-2">
                <strong>${{ cart.total|floatformat:2 }} + {{ cart.shipping_method.cost }}({{ cart.shipping_method.title }})</strong>
              </h4>
            </td>
            <td colspan="3" class="text-right">
              <button type="button" onclick="location.href='{% url 'order:checkout' %}'" class="btn btn-primary btn-rounded">Complete purchase
                <i class="fas fa-angle-right right"></i>
              </button>
            </td>
          </tr>
          <!-- Fourth row -->

        </tbody>
        <!-- /.Table body -->

      </table>

    </div>
    <!-- /.Shopping Cart table -->

  </div>

</div>


{% else %}
    <div class="container" style="margin-top: 25%">
        <div class="row justify-content-center align-items-center">
            <form class="col-12">
              <div class="form-group">
                  <h1 class="text text-center text-justify">Buy Some Products</h1>
                  <a class="btn btn-link btn-block text-center text-justify btn" href="{% url 'products:list' %}"> Click heare to visit Shop</a>
              </div>
            </form>
        </div>
    </div>
        {% endif %}

{% endblock %}