KartBox/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from products.views import FeaturedProduct

urlpatterns = [
    path('admin/', admin.site.urls),
    path('account/', include('account.urls')),
    path('products/', include('products.urls')),
    path('carts/', include('carts.urls')),
    path('', FeaturedProduct.as_view(), name='home'),
    path('order/', include('checkout.urls')),
    path('address/', include('addresses.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    # urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

addresses/urls.py
from django.urls import path
from .views import address_create

app_name = 'address'


urlpatterns = [
    path('', address_create, name='create'),
]

carts/urls.py
from django.conf.urls import url
from .views import add_cart, cart_detail, cart_remove, remove, cart_update, shippment_cost

app_name = 'carts'


urlpatterns = [
    url(r'^$', cart_detail, name='details'),
    url(r'^cart_add/(?P<product_id>[0-9]+)/$', add_cart, name='add'),
    url(r'^plus/(?P<product_id>[0-9]+)/$', cart_update, name='cart_plus'),
    url(r'^minus/(?P<product_id>[0-9]+)/$', cart_remove, name='cart_minus'),
    url(r'^remove/(?P<id>\d+)/$', remove, name='delete'),
    url(r'^shiping/$', shippment_cost, name='ship_cost'),
]

#

checkout/urls.py
from django.conf.urls import url
from .views import checkout_home, checkout_finish, checkout_success

app_name = 'order'

urlpatterns = [
    url(r'^$', checkout_home, name='checkout'),
    url(r'^done/$', checkout_finish, name='checkout_done'),
    url(r'^success/$', checkout_success, name='success')
]

products/urls.py
from django.urls import path
from .views import ProductList, ProductDetails

app_name = 'products'


urlpatterns = [
    path('list', ProductList.as_view(), name='list'),
    path('details/<slug:slug>', ProductDetails.as_view(), name='details'),
]

carts/models.py
from django.db import models
from django.conf import settings
from products.models import Product
from django.db.models.signals import pre_save, post_delete, post_save

User = settings.AUTH_USER_MODEL


class CartManager(models.Manager):
    def new_or_get(self, request):
        cart_id = request.session.get('cart_id', None)
        qs = self.get_queryset().filter(id=cart_id)
        if qs.count() == 1:
            new_obj = False
            cart_obj = qs.first()
            if request.user.is_authenticated and cart_obj.user is None:
                cart_obj.user = request.user
                cart_obj.save()
        else:
            cart_obj = self.new(user=request.user)
            new_obj = True
            request.session['cart_id'] = cart_obj.id

        return cart_obj, new_obj

    def new(self, user=None):
        user_obj = None
        if user is not None:
            if user.is_authenticated:
                user_obj = user
            else:
                user_obj = None
        return self.model.objects.create(user=user_obj)


class ShippingMethod(models.Model):
    title = models.CharField(max_length=25)
    cost = models.DecimalField(max_digits=10, decimal_places=2, default=0)

    def __str__(self):
        return self.title


class Cart(models.Model):
    user = models.ForeignKey(User, blank=True, null=True, on_delete=models.CASCADE)
    products = models.ManyToManyField(Product, blank=True)
    shipping_method = models.ForeignKey(ShippingMethod, blank=True, null=True, on_delete=models.SET_NULL)
    created = models.DateTimeField(auto_now_add=True, auto_now=False)
    updated = models.DateTimeField(auto_now_add=False, auto_now=True)
    active = models.BooleanField(default=True)
    total = models.DecimalField(max_digits=10, decimal_places=2, default=0)

    objects = CartManager()

    def __str__(self):
        return f'Cart Id: {self.pk}'


class CartItem(models.Model):
    cart = models.ForeignKey(Cart, null=True, blank=True, on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    quantity = models.PositiveIntegerField(default=0)
    total_item_price = models.DecimalField(max_digits=10, decimal_places=2, default=0)

    def __str__(self):
        return self.product.name


def get_single_total(instance, **kwargs):
        if int(instance.quantity) >= 1:
            total = float(instance.product.price) * int(instance.quantity)
            instance.total_item_price = total


pre_save.connect(get_single_total, sender=CartItem)


def user_presave(instance, **kwargs):
    if not instance.user:
        user = instance.user
        return user
    else:
        return instance.user


pre_save.connect(user_presave, sender=Cart)


def total_cost(instance, **kwargs):
    if instance.shipping_method:
        total = float(instance.total) + float(instance.shipping_method.cost)
        instance.total = total


pre_save.connect(total_cost, sender=Cart)

checkout/views.py
from django.shortcuts import render, redirect
from addresses.models import Address
from carts.models import Cart
from orders.models import Order
from django.contrib.auth.decorators import login_required
from billing.models import BillingProfile
from addresses.forms import AddressForm


@login_required(login_url='account:signin')
def checkout_home(request):
    cart, created = Cart.objects.new_or_get(request)
    order = None
    address = AddressForm()
    shipping_address_id = request.session.get('shipping_address_id', None)
    if created:
        return redirect('carts:details')
    billing_obj, created = BillingProfile.objects.new_or_get(request)
    address_qs = None
    if billing_obj is not None:
        address_qs = Address.objects.filter(billing_profile=billing_obj)
        order, created = Order.objects.new_or_get(billing_profile=billing_obj, cart=cart)
        if shipping_address_id:
            order.shipping_address = Address.objects.get(id=shipping_address_id)
            del request.session['shipping_address_id']
            order.save()
    # if request.method == 'POST':
    #     paid = order.checkout_done()
    #     if paid:
    #         order.mark_done()
    #         del request.session['cart_id']
    #         return redirect('/success')

    context = {
        'order_obj': order,
        'billing': billing_obj,
        'address_form': address,
        'address_qs': address_qs
    }
    return render(request, 'checkout/checkout.html', context)


@login_required(login_url='account:signin')
def checkout_finish(request):
    cart, created = Cart.objects.new_or_get(request)
    billing_obj, created = BillingProfile.objects.new_or_get(request)
    order = None
    if billing_obj is not None:
        order, created = Order.objects.new_or_get(billing_profile=billing_obj, cart=cart)
    paid = order.checkout_done()
    if paid:
        order.mark_done()
        del request.session['cart_id']
        return redirect('order:success')


def checkout_success(request):
    return render(request, 'checkout/thank_you.html', {})

checkout/templates/checkout/checkout.html
{% extends 'master.html' %}
{% load static %}
{% block title %}
Checkout|Home
{% endblock %}

{% block content %}

    <h1 style="margin-top: 6%" class="text-center font-weight-bold">Checkout</h1>
    {% if not order_obj.shipping_address %}
        <h1 class="ml-3">Shipping Address</h1>
        <form class="form" method="POST" action="{% url 'address:create' %}" novalidate>
            {% csrf_token %}


            {% if address_qs %}
            {% for address in address_qs %}
                <div class="mb-1">
                <label class="form-check-label ml-5" for="{{ address.id }}" onclick="hide()">
                    <input type="radio" id="{{ address.id }}" name="shipping_address" value="{{ address.id }}">
                    {{ address.get_full_address }}
                </label><br>
                </div>
            {% endfor %}
            {% endif %}
            <label for="form-visi" class="form-check-label ml-2" onclick="show()">
                <input id="form-visi" type="radio" name="shipping">Enter new address!
            </label><br>


            <div id="form" style="display: none" class="row">
                <div class="col-md-6 mb-1 p-4">
                    {{ address_form.as_p }}
                </div>
            </div>

            <div class="container">
                <button type="submit" class="btn btn-secondary">Submit</button>
            </div>

        </form>






    {% else %}
        <div class="card">
            <div class="center card card-body">
            <p>Order Total: {{ order_obj.total }}</p>
            <p>Shipping Total: {{ order_obj.cart.shipping_method.cost }} {{ order_obj.cart.shipping_method.title }}</p>
            <p>Address: {{ order_obj.shipping_address.get_full_address }}</p>
            <p class="font-weight-bold"><u>Items</u>
                {% for item in order_obj.cart.cartitem_set.all %}
                <ul>
                    <li>{{ item }}</li>
                </ul>
                {% endfor %}

            </p>
            <button class="btn btn-success" type="submit" onclick='window.location="{% url 'order:checkout_done' %}"'>Checkout</button>
        </div>
        </div>

    {% endif %}








    <style>
    .center{
        {#width: 60vw;#}
        {#height: 40vh;#}
        {#display: inline-flex;#}
        align-items: center;
        justify-content: space-between;
    }
    </style>
    <script type="text/javascript">
        function show() {
            document.getElementById('form').style.display = 'block'
        }
        function hide() {
            document.getElementById('form').style.display = 'none'
            document.getElementById('form-visi').checked = false
        }
    </script>
{% endblock %}

checkout/templates/checkout/thank_you.html
{% extends 'master.html' %}
{% block title %}
Thank You!
{% endblock %}


{% block content %}

    <div class="container" style="margin-top: 25%">
        <div class="row justify-content-center align-items-center">
            <form class="col-12">
              <div class="form-group">
                  <h1 class="text text-center text-justify">Thanks for Shopping!</h1>
                  <a class="btn btn-link btn-block text-center text-justify btn" href="{% url 'products:list' %}"> Click heare to buy again</a>
              </div>
            </form>
        </div>
    </div>


{% endblock %}