KartBox/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from products.views import FeaturedProduct

urlpatterns = [
    path('admin/', admin.site.urls),
    path('account/', include('account.urls')),
    path('products/', include('products.urls')),
    path('carts/', include('carts.urls')),
    path('', FeaturedProduct.as_view(), name='home'),
    path('order/', include('checkout.urls')),
    path('address/', include('addresses.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    # urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

account/urls.py
from django.conf.urls import url
from .views import Signup, Login
from django.contrib.auth.views import LogoutView
from django.urls import reverse_lazy

app_name = 'account'

urlpatterns = [
    url(r'^signup/$', Signup.as_view(), name='signup'),
    url(r'^signin/$', Login.as_view(), name='signin'),
    url(r'^logout/$', LogoutView.as_view(next_page=reverse_lazy('home')), name='logout'),
]

carts/urls.py
from django.conf.urls import url
from .views import add_cart, cart_detail, cart_remove, remove, cart_update, shippment_cost

app_name = 'carts'


urlpatterns = [
    url(r'^$', cart_detail, name='details'),
    url(r'^cart_add/(?P<product_id>[0-9]+)/$', add_cart, name='add'),
    url(r'^plus/(?P<product_id>[0-9]+)/$', cart_update, name='cart_plus'),
    url(r'^minus/(?P<product_id>[0-9]+)/$', cart_remove, name='cart_minus'),
    url(r'^remove/(?P<id>\d+)/$', remove, name='delete'),
    url(r'^shiping/$', shippment_cost, name='ship_cost'),
]

#

products/urls.py
from django.urls import path
from .views import ProductList, ProductDetails

app_name = 'products'


urlpatterns = [
    path('list', ProductList.as_view(), name='list'),
    path('details/<slug:slug>', ProductDetails.as_view(), name='details'),
]

templates/master3.html
<!DOCTYPE html>{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}

    {% endblock %}</title>
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'css/main.css' %}" type="text/css">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.3/css/all.css" integrity="sha384-UHRtZLI+pbxtHCWp1t77Bi1L4ZtiqrqD80Kn4Z8NTSRyMA2Fd33n5dQ8lWUE00s/" crossorigin="anonymous">

    {% block head %}

    {% endblock %}
</head>
<body>
<nav class="navbar navbar-expand-lg fixed-top mb-3 half-black">
  <a class="navbar-brand" href="#">KartBox</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="{% url 'home' %}">Home <span class="sr-only">(current)</span></a>
      </li>
        {% if user.is_authenticated %}
          <li class="nav-item">
              <a class="nav-link text-uppercase">{{ user.get_fullname }}</a>
          </li>
          <li>
            <a class="nav-link" href="{% url 'account:logout' %}">Logout</a>
          </li>
          {% else %}
            <li class="nav-item">
        <a class="nav-link" href="{% url 'account:signup' %}">Signup</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'account:signin' %}?next={{request.path}}">Signin</a>
      </li>
        {% endif %}

      <li class="nav-item">
        <a class="nav-link" href="{% url 'products:list' %}">Shop</a>
      </li>
        <li>
            <a class="nav-link" href="{% url 'carts:details' %}">
                <i class="fas fa-shopping-cart"></i> <span class="badge badge-light p-0">
{#              {{ request.session.count }}#}
                {% if cart_count %}
                {{ cart_count }}
                    {% else %}
                    0
                {% endif %}
            </span>
            </a>
        </li>
    </ul>
    <form class="form-inline my-2 my-lg-0">
      <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
    </form>
  </div>
</nav>
<div class="clearfix"></div>
<div class="container" id="bg-color-change">
    {% block content %}
        <h2 class="text text-center mt-5 pt-2">Featured Products</h2>
        <div class="card-columns mt-5">
        {% for object in object_list %}
            <div class="card">
                <img class="card-img card-img-top" src="{{ object.preview.url }}">
                <div>
                    <h4 class="card-title mt-3 p-3">{{ object.name }}</h4>
                    <p class="card-body text-justify">{{ object.des|truncatechars:40 }}</p>
                </div>
                <a class="btn btn-outline-dark btn-block" href="{% url 'products:details' slug=object.slug %}">View</a>
            </div>
        {% endfor %}
        </div>

    {% endblock %}
</div>
{% block js %}

{% endblock %}

<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>

</body>
</html>