KartBox/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from products.views import FeaturedProduct

urlpatterns = [
    path('admin/', admin.site.urls),
    path('account/', include('account.urls')),
    path('products/', include('products.urls')),
    path('carts/', include('carts.urls')),
    path('', FeaturedProduct.as_view(), name='home'),
    path('order/', include('checkout.urls')),
    path('address/', include('addresses.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    # urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

carts/urls.py
from django.conf.urls import url
from .views import add_cart, cart_detail, cart_remove, remove, cart_update, shippment_cost

app_name = 'carts'


urlpatterns = [
    url(r'^$', cart_detail, name='details'),
    url(r'^cart_add/(?P<product_id>[0-9]+)/$', add_cart, name='add'),
    url(r'^plus/(?P<product_id>[0-9]+)/$', cart_update, name='cart_plus'),
    url(r'^minus/(?P<product_id>[0-9]+)/$', cart_remove, name='cart_minus'),
    url(r'^remove/(?P<id>\d+)/$', remove, name='delete'),
    url(r'^shiping/$', shippment_cost, name='ship_cost'),
]

#

products/urls.py
from django.urls import path
from .views import ProductList, ProductDetails

app_name = 'products'


urlpatterns = [
    path('list', ProductList.as_view(), name='list'),
    path('details/<slug:slug>', ProductDetails.as_view(), name='details'),
]

products/models.py
from django.db import models
from django.shortcuts import reverse
from .utils import unique_slug_generator
from django.db.models.signals import pre_save


class ProductManager(models.Manager):
    def featured(self):
        return self.get_queryset().filter(featured=True)


class Product(models.Model):
    name = models.CharField(max_length=200, db_index=True)
    slug = models.SlugField(unique=True, blank=True)
    des = models.TextField()
    price = models.DecimalField(max_digits=10, decimal_places=2)
    preview = models.ImageField(upload_to='media/%Y/%m/%d', blank=False)
    featured = models.BooleanField(default=False)

    objects = ProductManager()

    def __str__(self):
        return self.name.capitalize()

    def get_absolute_url(self):
        return reverse('products:details', args=[self.slug])


class Image(models.Model):
    product = models.ForeignKey(Product, default=None, related_name='images', on_delete=models.CASCADE)
    image = models.ImageField(upload_to='media/%Y/%m/%d', blank=True)

    def __str__(self):
        return self.product.name.capitalize()


def slugify_product_slug(sender, instance, *args, **kwargs):
    if not instance.slug:
        instance.slug = unique_slug_generator(instance)
    # slug = slugify(instance.name)
    # exists = Product.objects.filter(slug=slug).exists()
    # if exists:
    #     slug = '%s-%s' %(slug, instance.id)
    # instance.slug = slug


pre_save.connect(slugify_product_slug, sender=Product)

products/views.py
from django.views.generic import DetailView, ListView
from .models import Product


class ProductList(ListView):
    model = Product


class ProductDetails(DetailView):
    model = Product


class FeaturedProduct(ListView):
    template_name = 'master.html'
    queryset = Product.objects.featured()

products/templates/products/product_detail.html
{% extends 'master.html' %}
{% load static %}

{% block title %}
{{product.name}}
{% endblock %}



{% block content %}

    <div class="row mt-5">
        <div class="col-lg-6 mt-5">
            <div id="carouselExampleControls" class="carousel slide" data-ride="carousel">
              <div class="carousel-inner">
                  {% for img in product.images.all %}
                      {% if img and forloop.counter == 1 %}
                <div class="carousel-item active">
                  <img class="d-block w-100" src="{{ img.image.url }}" alt="First slide" width="540" height="400">
                </div>
                          {% else %}
                          <div class="carousel-item">
                  <img class="d-block w-100" src="{{ img.image.url }}" alt="First slide" width="540" height="400">
                </div>
                      {% endif %}
                  {% endfor %}

              </div>
              <a class="carousel-control-prev" href="#carouselExampleControls" role="button" data-slide="prev">
                <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                <span class="sr-only">Previous</span>
              </a>
              <a class="carousel-control-next" href="#carouselExampleControls" role="button" data-slide="next">
                <span class="carousel-control-next-icon" aria-hidden="true"></span>
                <span class="sr-only">Next</span>
              </a>
            </div>
        </div>
{############################        slider end     ###########################}
        <div class="col-lg-6 mt-5 p-3">
            <h2 class="text">{{ product.name.capitalize }}</h2>
            <p class="text text-justify">{{ product.des|truncatechars:260 }}</p>
            <p class="text font-weight-bold">$ {{ product.price }}</p>
{#            <a type="submit" href="{% url 'carts:update' product_id=product.id %}">Add Cart</a>#}
            <form method="post" action="{% url 'carts:add' product_id=product.id %}">
                {% csrf_token %}
                <input type="number" class="btn btn-outline-dark" name="qty" min="0" value="1">
                <input type="submit" class="btn btn-success ml-2" value="Add Cart">
            </form>
        </div>
    <div class="clearfix"></div>

    <div class="col-lg-12">
        <h2 class="text-center mt-5">Description</h2>
         <p class="text-justify mt-3">{{ product.des }}</p>
    </div>
    </div>

{% endblock %}

products/templates/products/product_list.html
{% extends 'master.html' %}
{% load static %}
{% block title %}
Product|List
{% endblock %}




{#{% block content %}#}
{#    <h1 class="text bg-transparent text-center mt-5 pt-3">Products</h1>#}
{#<div class="card-columns mt-5">#}
{#     {% for product in product_list %}#}
{#    <div class="card">#}
{#    {% if product.preview %}#}
{#        <img class="card-img card-img-top p-1" src="{{ product.preview.url }}" width="200" height="300">#}
{#    {% endif %}#}
{#        <div class="card-body">#}
{#            <h5 class="card-title mt-3">{{ product.name }}</h5>#}
{#            <p class="card-text">{{ product.des|truncatechars:50 }}</p>#}
{#        </div>#}
{#    <a href="{% url 'products:details' slug=product.slug %}" class="btn btn-block btn-success m-0">View</a>#}
{#    </div>#}
{##}
{#    {% endfor %}#}
{#</div>#}
{#{% endblock %}#}
{% block content %}
 <!--Main layout-->
  <main style="padding-top: 70px">
    <div class="container">

      <!--Navbar-->
      <nav class="navbar navbar-expand-lg navbar-dark mdb-color lighten-3 mt-3 mb-5">

        <!-- Navbar brand -->
        <span class="navbar-brand">Categories:</span>

        <!-- Collapse button -->
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#basicExampleNav"
          aria-controls="basicExampleNav" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>

        <!-- Collapsible content -->
        <div class="collapse navbar-collapse" id="basicExampleNav">

          <!-- Links -->
          <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
              <a class="nav-link" href="#">All
                <span class="sr-only">(current)</span>
              </a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="#">Shirts</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="#">Sport wears</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="#">Outwears</a>
            </li>

          </ul>
          <!-- Links -->

          <form class="form-inline">
            <div class="md-form my-0">
              <input class="form-control mr-sm-2" type="text" placeholder="Search" aria-label="Search">
            </div>
          </form>
        </div>
        <!-- Collapsible content -->

      </nav>
      <!--/.Navbar-->

      <!--Section: Products v.3-->
      <section class="text-center mb-4">

        <!--Grid row-->
        <div class="row wow fadeIn d-flex">
{#<h2 class="text-center clearfix">Featured Products</h2>#}
          <!--Grid column-->
          <div class="col-lg-3 col-md-6 mb-4">
        {% for object in object_list %}
            <!--Card-->
            <div class="card" onclick="location.href='{% url 'products:details' slug=object.slug %}'">
              <!--Card image-->
              <div class="view overlay">
                <img src="{{ object.preview.url }}" style="width: 100%;height: 140px" class="card-img-top" alt="">
                <a>
                  <div class="mask rgba-white-slight"></div>
                </a>
              </div>
              <!--Card image-->

              <!--Card content-->
              <div class="card-body text-center">
                <!--Category & Title-->
                <a href="" class="grey-text">
                  <h5>Shirt</h5>
                </a>
                <h5>
                  <strong>
                    <a href="" class="dark-grey-text">{{ object.name }}
                      <span class="badge badge-pill danger-color">NEW</span>
                    </a>
                  </strong>
                </h5>

                <h4 class="font-weight-bold blue-text">
                  <strong>{{ object.price }}$</strong>
                </h4>

              </div>
              <!--Card content-->

            </div>
            <!--Card-->
          </div>
        {% endfor %}
          <!--Grid column-->
        </div>
        <!--Grid row-->

      </section>
      <!--Section: Products v.3-->

      <!--Pagination-->
      <nav class="d-flex justify-content-center wow fadeIn">
        <ul class="pagination pg-blue">

          <!--Arrow left-->
          <li class="page-item disabled">
            <a class="page-link" href="#" aria-label="Previous">
              <span aria-hidden="true">&laquo;</span>
              <span class="sr-only">Previous</span>
            </a>
          </li>

          <li class="page-item active">
            <a class="page-link" href="#">1
              <span class="sr-only">(current)</span>
            </a>
          </li>
          <li class="page-item">
            <a class="page-link" href="#">2</a>
          </li>
          <li class="page-item">
            <a class="page-link" href="#">3</a>
          </li>
          <li class="page-item">
            <a class="page-link" href="#">4</a>
          </li>
          <li class="page-item">
            <a class="page-link" href="#">5</a>
          </li>

          <li class="page-item">
            <a class="page-link" href="#" aria-label="Next">
              <span aria-hidden="true">&raquo;</span>
              <span class="sr-only">Next</span>
            </a>
          </li>
        </ul>
      </nav>
      <!--Pagination-->

    </div>
  </main>
  <!--Main layout-->

{% endblock %}